<h1>Storage API</h1>

<a href="<?php echo $this->url(array("action" => "index", "controller" => "storage")) ?>">List items</a><br/>
<a href="<?php echo $this->url(array("action" => "upload", "controller" => "storage")) ?>">Upload item</a><br/>

<h1>Queue API</h1>

<a href="<?php echo $this->url(array("action" => "index", "controller" => "queue")) ?>">List queues</a><br/>
<a href="<?php echo $this->url(array("action" => "create", "controller" => "queue")) ?>">Create queue</a><br/>
<a href="<?php echo $this->url(array("action" => "send", "controller" => "queue")) ?>">Send messages</a><br/>
<a href="<?php echo $this->url(array("action" => "receive", "controller" => "queue")) ?>">Receive messages</a><br/>

<h1>Document API</h1>

<a href="<?php echo $this->url(array("action" => "index", "controller" => "document")) ?>">List collections</a><br/>
<a href="<?php echo $this->url(array("action" => "create", "controller" => "document")) ?>">Create collection</a><br/>

