<?php 
if (count($this->qs) == 0) {
	echo "No queues.";
	return;
}
?>
<?php foreach ($this->qs as $queue): ?>
<form method="POST" action="<?php echo $this->url(array("action" => "send", "controller" => "queue")) ?>" style="display: inline">
Queue <?php echo $queue ?>: 
<input type="hidden" name="name" value="<?php echo $queue ?>">
<input type="submit" value="Send" style="display: inline">
</form> 
<form method="POST" action="<?php echo $this->url(array("action" => "receive", "controller" => "queue")) ?>" style="display: inline">
<input type="hidden" name="name" value="<?php echo $queue ?>">
<input type="submit" value="Receive" style="display: inline">
</form> 
<br/>
<?php endforeach; ?>
